project:
  type: website

website:
  page-navigation: false
  title: "R for Statistical Data Science"
  site-url: "https://r-programming-course.netlify.app"
  repo-url: https://github.com/maeveupton/UL-MS6071
  repo-actions: [issue, edit]
  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Steven Golovkine & Maeve Upton"
    background: "#fdf5e6"

  sidebar:
    background: "#fdf5e6"
    logo: "./include/logo.svg"
    pinned: true
    align: center
    toc-location: right
    tools:
      - icon: github
        href: https://github.com/maeveupton/UL-MS6071
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Topics"
        contents:
          - href: weeks/week-1.qmd
            text: "1 - R Basics"


bibliography: bibliography.bib

format:
  html:
    theme:
      light: [cosmo]
    css:
    - ./ul.css
    - include/webex.css
    code-copy: true
    code-overflow: wrap
    toc: true
    smooth-scroll: true
    include-after-body: include/webex.js


freeze: auto

editor: visual
