---
title: "MS6071 -- R for Statistical Data Science"
tbl-colwidths: [5,5,5,5,5,5]
---

<br>

This page contains different topics related to R for statistical data science. The content covers a range of subjects that are fundamental to understanding and applying R in the context of data analysis and statistics. While these topics offer a broad overview, they are not exhaustive, and you may encounter other areas that are equally compelling and relevant to your work in data science.

| Topic | Key Notes | MCQ | Lab | Lab solutions | Source code |
|----|:--:|:--:|:--:|:--:|:--:|
| R Basics | [🖥️](/weeks/week-1.qmd "Contents week 1"){aria-label="Contents week 1"} | [📋](/questionnaire/qcm-week-1.qmd "MCQ Week 1"){aria-label="MCQ Week 1"} | [💻](/labs/lab-week-1.qmd "Labs Week 1"){aria-label="Labs Week 1"} | [💻](/labs/solutions/week-1.R "Labs Solution Week 1"){aria-label="Labs Sol Week 1"} | [🧑‍💻](/contents/week-1/source/all_code_chunks.R "Source Code Week 1"){aria-label="Source Code Week 1"} |
| Tidyverse | [🖥️](/weeks/week-2.qmd "Contents week 2"){aria-label="Contents week 2"} | [📋](/questionnaire/qcm-week-2.qmd "MCQ Week 2"){aria-label="MCQ Week 2"} | [💻](/labs/lab-week-2.qmd "Labs Week 2"){aria-label="Labs Week 2"} | [💻](/labs/solutions/week-2.R "Labs Solution Week 2"){aria-label="Labs Sol Week 2"} | [🧑‍💻](/contents/week-2/source/all_code_chunks.R "Source Code Week 2"){aria-label="Source Code Week 2"} |
| ETL | [🖥](/weeks/week-3.qmd "Contents week 3"){aria-label="Contents week 3"}| [📋](/questionnaire/qcm-week-3.qmd "MCQ Week 3"){aria-label="MCQ Week 3"} | [💻](/labs/lab-week-3.qmd "Labs Week 3"){aria-label="Labs Week 3"} | [💻](/labs/solutions/week-3.R "Labs Solution Week 3"){aria-label="Labs Sol Week 3"} | [🧑‍💻](/contents/week-3/source/all_code_chunks.R "Source Code Week 3"){aria-label="Source Code Week 3"} |
| Data Visualisation | [🖥️](/weeks/week-4.qmd "Contents week 4"){aria-label="Contents week 4"} | [📋](/questionnaire/qcm-week-4.qmd "MCQ Week 4"){aria-label="MCQ Week 4"} | [💻](/labs/lab-week-4.qmd "Labs Week 4"){aria-label="Labs Week 4"} | [💻](/labs/solutions/week-4.R "Labs Solution Week 4"){aria-label="Labs Sol Week 4"} |
| Reproducibility | [🖥️](/weeks/week-5.qmd "Contents week 5"){aria-label="Contents week 5"} | [📋](/questionnaire/qcm-week-5.qmd "MCQ Week 5"){aria-label="MCQ Week 5"} |  |  | [🧑‍💻](/contents/week-5/source/all_code_chunks.R "Source Code Week 5"){aria-label="Source Code Week 5"} || Interactivity | [🖥️](/weeks/week-6.qmd "Contents week 6"){aria-label="Contents week 6"} | [📋](/questionnaire/qcm-week-6.qmd "MCQ Week 6"){aria-label="MCQ Week 6"} | [💻](/labs/lab-week-6.qmd "Labs Week 6"){aria-label="Labs Week 6"} | [💻](/labs/solutions/week-6.Rmd "Labs Solution Week 6"){aria-label="Labs Sol Week 6"} | [🧑‍💻](/contents/week-6/source/all_code_chunks.R "Source Code Week 6"){aria-label="Source Code Week 6"} |
