---
title: "R Basics"
editor: visual
---

**R** is a software environment for statistical analysis and data visualization. It is free, open source and available on macOS, Windows and Linux. It is regularly being updated and new packages are released everyday on the Comprehensive R Archive Network ([CRAN](https://cloud.r-project.org/web/packages/available_packages_by_date.html)) to enhance its capabilities. As of today, there are around $20000$ available packages.

Prior to diving into the materials, ensure that you have R and RStudio installed. You can find instructions on their installation [here](/information/faq.qmd). If you need any help, don't hesitate to contact me.

## Prepare

📖 [Quick history of R](/contents/week-1/00_History_of_R.qmd)

📖 [Getting started with R and RStudio](/contents/week-1/01_Getting_Started.qmd)

📖 [R Basics](/contents/week-1/01_R_Basics.qmd)

📖 [R Objects](/contents/week-1/02_R_Objects.qmd)

📖 [Logical Operators](/contents/week-1/03_Logical_Ops.qmd)

📖 [Vectors](/contents/week-1/04_Vectors.qmd)

📖 [Lists](/contents/week-1/05_Lists.qmd)

📖 [Functions](/contents/week-1/06_Functions.qmd)

📖 [Conditional Statements](/contents/week-1/07_If_Else.qmd)

📖 [Loops](/contents/week-1/08_Loops.qmd)

📖 [Dataframes](/contents/week-1/09_Dataframes.qmd)

📖 [Packages](/contents/week-1/10_Packages.qmd)

## Source code

🧑‍💻 [Source code](/contents/week-1/source/all_code_chunks.R)

## Questionnaire

📋 [Questionnaire](/questionnaire/qcm-week-1.qmd)

## Practice

⌨️ [Tutorial](/labs/lab-week-1.qmd)

⌨️ [Solution proposal](/labs/solutions/week-1.R)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
